# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b9c011802f5c65d4fe509d227ab54a17f83e598c89deaa5b0a1f8132dc67b3b0ba707f023cbd0f90b28dbb7f5fd84ed0dc62648904c1b8f675264f65cf114ab

test:
  secret_key_base: 95cd88b6b2da4b3c13642c002f35361382221f93915163c0c58a138b561094161eb99dee68aadc5751e1c567e0ffb9fc9a692e8da6e14ef554bf1883514e0b42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
